version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-orders"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11otlm1qgtcw0"
s3_prefix = "lambda-orders"
region = "eu-west-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "UtilsLayerArn=\"arn:aws:lambda:eu-west-1:640339490701:layer:utils-layer:2"
image_repositories = []
